rule Main:
    conda:
        "pypsa-eur/envs/environment.yaml"
    shell:
        ( "snakemake"
          " --directory=pypsa-eur-sec/"
          " --snakefile=pypsa-eur-sec/Snakefile"
          " -j1"
          " prepare_sector_networks"
        )
