# NB: this name is used in the status badge
name: "Tests, code style & coverage"

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - dev
      - main

# Copied from travis.yml, might need to be re-included
#env:
#  global:
#    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
#    - SEGFAULT_SIGNALS=all
#    - LANG=en_US.UTF-8

jobs:
  build:
    name: Python ${{ matrix.python-version }} (${{ matrix.platform }})
    runs-on: ${{ matrix.platform }}

    strategy:
      matrix:
        python-version:
          - "3.8"
        platform: [ubuntu-latest, macos-latest]
        exclude:
          - platform: macos-latest
            python-version: "3.8"
      max-parallel: 4
      fail-fast: false

    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Install dependencies"
        run: |
          python -mpip install --progress-bar=off tox tox-gh-actions -r'ci/requirements.txt'
          virtualenv --version
          pip --version
          tox --version
      - name: "Run tox targets for ${{ matrix.python-version }}"
        run: "python -m tox -vv"
        env:
          PLATFORM: ${{ matrix.platform }}
